# Generated by Django 5.1.7 on 2025-03-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_genero_album_auditoria_cancion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
