# Generated by Django 5.1.7 on 2025-03-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auditoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
