# Generated by Django 5.1.7 on 2025-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_delete_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='duracion',
            field=models.CharField(default='00:00', max_length=50),
        ),
        migrations.AddField(
            model_name='cancion',
            name='portada',
            field=models.CharField(default='ruta', max_length=300),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=300),
        ),
    ]
