# Generated by Django 5.1.7 on 2025-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_cancion_duracion_cancion_portada_usuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='portada',
            field=models.ImageField(default='ruta', max_length=300, upload_to=''),
        ),
    ]
