# Generated by Django 5.1.7 on 2025-05-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_cancion_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
