# Generated by Django 5.1.7 on 2025-05-20 02:53

import Usuario.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_alter_cancion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='portada',
            field=models.ImageField(default='ruta', max_length=300, storage=Usuario.storage.OverwriteStorage(), upload_to='portadas/'),
        ),
    ]
