# Generated by Django 5.1.7 on 2025-05-20 15:32

import Usuario.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_alter_cancion_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(default='ruta', max_length=300, storage=Usuario.storage.OverwriteStorage(), upload_to='canciones/'),
        ),
    ]
