# Generated by Django 5.1.7 on 2025-05-21 19:57

import Usuario.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_alter_cancion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.ImageField(default='ruta', max_length=300, storage=Usuario.storage.OverwriteStorage(), upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='ruta', max_length=300, storage=Usuario.storage.OverwriteStorage(), upload_to='Foto_perfiles/'),
        ),
    ]
