# Generated by Django 5.1.7 on 2025-05-27 03:43

import Usuario.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_alter_album_portada_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='portada',
            field=models.ImageField(default='ruta', max_length=300, storage=Usuario.storage.OverwriteStorage(), upload_to='portadas/'),
        ),
    ]
